export const NOTIFICATION_TYPE_LABELS: Record<string, string> = {
  COMMUNITY_INVITED: 'Lời mời cộng đồng',
  COMMUNITY_ROLE_PROMOTED: 'Được thăng quyền',
  COMMUNITY_ROLE_DEMOTED: 'Bị hạ quyền',
  COMMUNITY_KICKED: 'Bị mời khỏi cộng đồng',
  COMMUNITY_INVITE_REVOKED: 'Lời mời bị thu hồi',
  COMMUNITY_OWNERSHIP_TRANSFERRED: 'Nhận quyền sở hữu',
  COMMUNITY_BANNED: 'Bị cấm khỏi cộng đồng',
  COMMUNITY_UNBANNED: 'Được gỡ cấm',
  TOURNAMENT_REGISTER_PENDING: 'Chờ duyệt',
  TOURNAMENT_REGISTER_SUCCESS: 'Đăng ký thành công',
  TOURNAMENT_REGISTER_REJECTED: 'Đăng ký bị từ chối',
  TOURNAMENT_PARTICIPANT_NEW: 'Đăng ký mới',
  TOURNAMENT_TEAM_PENDING: 'Chờ đồng đội',
  TOURNAMENT_TEAM_COMPLETED: 'Đội đã hoàn tất',
  TOURNAMENT_TEAMMATE_JOINED: 'Đồng đội tham gia',
  TOURNAMENT_WITHDRAWN: 'Rút đăng ký',
  TOURNAMENT_KICKED: 'Bị loại',
  TOURNAMENT_FULL_CANCELLED: 'Hủy do đầy slot',
  TOURNAMENT_TEAM_TIMEOUT: 'Hết hạn xác nhận',
  TOURNAMENT_PAYMENT_COMPLETED: 'Thanh toán',
  TOURNAMENT_CANCELLED: 'Giải bị hủy',
  TOURNAMENT_RESERVED_SLOT_ASSIGNED: 'Được giữ chỗ',
  TOURNAMENT_PUBLISH_APPROVED: 'Được mở đăng ký',
  TOURNAMENT_PUBLISH_REJECTED: 'Bị từ chối duyệt',
  TOURNAMENT_SUSPENDED: 'Bị đình chỉ',
  TOURNAMENT_UNSUSPENDED: 'Được khôi phục',
  TOURNAMENT_DELETE_APPROVED: 'Xóa giải được duyệt',
  TOURNAMENT_DELETE_REJECTED: 'Xóa giải bị từ chối',
  VERIFICATION_APPROVED: 'Xác minh được duyệt',
  VERIFICATION_REJECTED: 'Xác minh bị từ chối',
  USER_BANNED: 'Tài khoản bị hạn chế',
  USER_UNBANNED: 'Tài khoản được khôi phục',
  MATCH_SCHEDULED: 'Lịch thi đấu',
  MATCH_COMPLETED: 'Kết quả trận',
  REFEREE_INVITED: 'Lời mời trọng tài',
  REFEREE_INVITE_REVOKED: 'Lời mời bị thu hồi',
  REFEREE_INVITE_ACCEPTED: 'Trọng tài đã nhận lời',
  REFEREE_INVITE_DECLINED: 'Trọng tài từ chối',
  REFEREE_ASSIGNED: 'Phân công trọng tài',
  PAYOUT_APPROVED: 'Rút tiền được duyệt',
  PAYOUT_REJECTED: 'Rút tiền bị từ chối',
};

export interface NotificationTypeMeta {
  badgeClassName: string;
  cardClassName: string;
  unreadCardClassName: string;
  dotClassName: string;
}

export const NOTIFICATION_TYPE_META: Record<string, NotificationTypeMeta> = {
  COMMUNITY_INVITED: {
    badgeClassName: 'bg-blue-100 text-blue-800',
    cardClassName: 'hover:border-blue-200 hover:bg-blue-50/50',
    unreadCardClassName: 'border-blue-200 bg-blue-50/80 shadow-sm',
    dotClassName: 'bg-blue-500',
  },
  COMMUNITY_ROLE_PROMOTED: {
    badgeClassName: 'bg-blue-100 text-blue-800',
    cardClassName: 'hover:border-blue-200 hover:bg-blue-50/50',
    unreadCardClassName: 'border-blue-200 bg-blue-50/75 shadow-sm',
    dotClassName: 'bg-blue-500',
  },
  COMMUNITY_ROLE_DEMOTED: {
    badgeClassName: 'bg-amber-100 text-amber-800',
    cardClassName: 'hover:border-amber-200 hover:bg-amber-50/50',
    unreadCardClassName: 'border-amber-200 bg-amber-50/75 shadow-sm',
    dotClassName: 'bg-amber-500',
  },
  COMMUNITY_KICKED: {
    badgeClassName: 'bg-rose-100 text-rose-800',
    cardClassName: 'hover:border-rose-200 hover:bg-rose-50/50',
    unreadCardClassName: 'border-slate-200 bg-rose-50/75 shadow-sm',
    dotClassName: 'bg-rose-500',
  },
  COMMUNITY_INVITE_REVOKED: {
    badgeClassName: 'bg-slate-200 text-slate-700',
    cardClassName: 'hover:border-slate-300 hover:bg-slate-50',
    unreadCardClassName: 'border-slate-300 bg-slate-100 shadow-sm',
    dotClassName: 'bg-slate-500',
  },
  COMMUNITY_OWNERSHIP_TRANSFERRED: {
    badgeClassName: 'bg-amber-100 text-amber-800',
    cardClassName: 'hover:border-amber-200 hover:bg-amber-50/50',
    unreadCardClassName: 'border-amber-200 bg-amber-50/75 shadow-sm',
    dotClassName: 'bg-amber-500',
  },
  COMMUNITY_BANNED: {
    badgeClassName: 'bg-rose-100 text-rose-800',
    cardClassName: 'hover:border-rose-200 hover:bg-rose-50/50',
    unreadCardClassName: 'border-slate-200 bg-rose-50/75 shadow-sm',
    dotClassName: 'bg-rose-500',
  },
  COMMUNITY_UNBANNED: {
    badgeClassName: 'bg-blue-100 text-blue-800',
    cardClassName: 'hover:border-blue-200 hover:bg-blue-50/50',
    unreadCardClassName: 'border-blue-200 bg-blue-50/75 shadow-sm',
    dotClassName: 'bg-blue-500',
  },
  TOURNAMENT_REGISTER_PENDING: {
    badgeClassName: 'bg-amber-100 text-amber-800',
    cardClassName: 'hover:border-amber-200 hover:bg-amber-50/50',
    unreadCardClassName: 'border-amber-200 bg-amber-50/70 shadow-sm',
    dotClassName: 'bg-amber-500',
  },
  TOURNAMENT_REGISTER_REJECTED: {
    badgeClassName: 'bg-rose-100 text-rose-800',
    cardClassName: 'hover:border-rose-200 hover:bg-rose-50/50',
    unreadCardClassName: 'border-slate-200 bg-rose-50/70 shadow-sm',
    dotClassName: 'bg-rose-500',
  },
  TOURNAMENT_KICKED: {
    badgeClassName: 'bg-rose-100 text-rose-800',
    cardClassName: 'hover:border-rose-200 hover:bg-rose-50/50',
    unreadCardClassName: 'border-slate-200 bg-rose-50/70 shadow-sm',
    dotClassName: 'bg-rose-500',
  },
  TOURNAMENT_CANCELLED: {
    badgeClassName: 'bg-rose-100 text-rose-800',
    cardClassName: 'hover:border-rose-200 hover:bg-rose-50/50',
    unreadCardClassName: 'border-slate-200 bg-rose-50/70 shadow-sm',
    dotClassName: 'bg-rose-500',
  },
  TOURNAMENT_RESERVED_SLOT_ASSIGNED: {
    badgeClassName: 'bg-blue-100 text-blue-800',
    cardClassName: 'hover:border-blue-200 hover:bg-blue-50/50',
    unreadCardClassName: 'border-blue-200 bg-blue-50/70 shadow-sm',
    dotClassName: 'bg-blue-500',
  },
  TOURNAMENT_PUBLISH_APPROVED: {
    badgeClassName: 'bg-emerald-100 text-emerald-800',
    cardClassName: 'hover:border-emerald-200 hover:bg-emerald-50/50',
    unreadCardClassName: 'border-emerald-200 bg-emerald-50/70 shadow-sm',
    dotClassName: 'bg-emerald-500',
  },
  TOURNAMENT_PUBLISH_REJECTED: {
    badgeClassName: 'bg-rose-100 text-rose-800',
    cardClassName: 'hover:border-rose-200 hover:bg-rose-50/50',
    unreadCardClassName: 'border-slate-200 bg-rose-50/70 shadow-sm',
    dotClassName: 'bg-rose-500',
  },
  TOURNAMENT_SUSPENDED: {
    badgeClassName: 'bg-amber-100 text-amber-800',
    cardClassName: 'hover:border-amber-200 hover:bg-amber-50/50',
    unreadCardClassName: 'border-amber-200 bg-amber-50/70 shadow-sm',
    dotClassName: 'bg-amber-500',
  },
  TOURNAMENT_UNSUSPENDED: {
    badgeClassName: 'bg-blue-100 text-blue-800',
    cardClassName: 'hover:border-blue-200 hover:bg-blue-50/50',
    unreadCardClassName: 'border-blue-200 bg-blue-50/70 shadow-sm',
    dotClassName: 'bg-blue-500',
  },
  TOURNAMENT_DELETE_APPROVED: {
    badgeClassName: 'bg-slate-200 text-slate-800',
    cardClassName: 'hover:border-slate-300 hover:bg-slate-50',
    unreadCardClassName: 'border-slate-300 bg-slate-100 shadow-sm',
    dotClassName: 'bg-slate-500',
  },
  TOURNAMENT_DELETE_REJECTED: {
    badgeClassName: 'bg-amber-100 text-amber-800',
    cardClassName: 'hover:border-amber-200 hover:bg-amber-50/50',
    unreadCardClassName: 'border-amber-200 bg-amber-50/70 shadow-sm',
    dotClassName: 'bg-amber-500',
  },
  VERIFICATION_APPROVED: {
    badgeClassName: 'bg-emerald-100 text-emerald-800',
    cardClassName: 'hover:border-emerald-200 hover:bg-emerald-50/50',
    unreadCardClassName: 'border-emerald-200 bg-emerald-50/70 shadow-sm',
    dotClassName: 'bg-emerald-500',
  },
  VERIFICATION_REJECTED: {
    badgeClassName: 'bg-rose-100 text-rose-800',
    cardClassName: 'hover:border-rose-200 hover:bg-rose-50/50',
    unreadCardClassName: 'border-slate-200 bg-rose-50/70 shadow-sm',
    dotClassName: 'bg-rose-500',
  },
  USER_BANNED: {
    badgeClassName: 'bg-rose-100 text-rose-800',
    cardClassName: 'hover:border-rose-200 hover:bg-rose-50/50',
    unreadCardClassName: 'border-slate-200 bg-rose-50/70 shadow-sm',
    dotClassName: 'bg-rose-500',
  },
  USER_UNBANNED: {
    badgeClassName: 'bg-blue-100 text-blue-800',
    cardClassName: 'hover:border-blue-200 hover:bg-blue-50/50',
    unreadCardClassName: 'border-blue-200 bg-blue-50/70 shadow-sm',
    dotClassName: 'bg-blue-500',
  },
  TOURNAMENT_PAYMENT_COMPLETED: {
    badgeClassName: 'bg-emerald-100 text-emerald-800',
    cardClassName: 'hover:border-emerald-200 hover:bg-emerald-50/50',
    unreadCardClassName: 'border-emerald-200 bg-emerald-50/70 shadow-sm',
    dotClassName: 'bg-emerald-500',
  },
  PAYOUT_APPROVED: {
    badgeClassName: 'bg-emerald-100 text-emerald-800',
    cardClassName: 'hover:border-emerald-200 hover:bg-emerald-50/50',
    unreadCardClassName: 'border-emerald-200 bg-emerald-50/70 shadow-sm',
    dotClassName: 'bg-emerald-500',
  },
  PAYOUT_REJECTED: {
    badgeClassName: 'bg-rose-100 text-rose-800',
    cardClassName: 'hover:border-rose-200 hover:bg-rose-50/50',
    unreadCardClassName: 'border-slate-200 bg-rose-50/70 shadow-sm',
    dotClassName: 'bg-rose-500',
  },
  MATCH_SCHEDULED: {
    badgeClassName: 'bg-blue-100 text-blue-800',
    cardClassName: 'hover:border-blue-200 hover:bg-blue-50/50',
    unreadCardClassName: 'border-blue-200 bg-blue-50/70 shadow-sm',
    dotClassName: 'bg-blue-500',
  },
  MATCH_COMPLETED: {
    badgeClassName: 'bg-blue-100 text-blue-800',
    cardClassName: 'hover:border-blue-200 hover:bg-blue-50/50',
    unreadCardClassName: 'border-blue-200 bg-blue-50/70 shadow-sm',
    dotClassName: 'bg-blue-500',
  },
  REFEREE_INVITED: {
    badgeClassName: 'bg-amber-100 text-amber-800',
    cardClassName: 'hover:border-amber-200 hover:bg-amber-50/50',
    unreadCardClassName: 'border-amber-200 bg-amber-50/70 shadow-sm',
    dotClassName: 'bg-amber-500',
  },
  REFEREE_INVITE_REVOKED: {
    badgeClassName: 'bg-slate-200 text-slate-700',
    cardClassName: 'hover:border-slate-300 hover:bg-slate-50',
    unreadCardClassName: 'border-slate-300 bg-slate-100 shadow-sm',
    dotClassName: 'bg-slate-500',
  },
  REFEREE_INVITE_ACCEPTED: {
    badgeClassName: 'bg-emerald-100 text-emerald-800',
    cardClassName: 'hover:border-emerald-200 hover:bg-emerald-50/50',
    unreadCardClassName: 'border-emerald-200 bg-emerald-50/70 shadow-sm',
    dotClassName: 'bg-emerald-500',
  },
  REFEREE_INVITE_DECLINED: {
    badgeClassName: 'bg-rose-100 text-rose-800',
    cardClassName: 'hover:border-rose-200 hover:bg-rose-50/50',
    unreadCardClassName: 'border-slate-200 bg-rose-50/70 shadow-sm',
    dotClassName: 'bg-rose-500',
  },
  REFEREE_ASSIGNED: {
    badgeClassName: 'bg-blue-100 text-blue-800',
    cardClassName: 'hover:border-blue-200 hover:bg-blue-50/50',
    unreadCardClassName: 'border-blue-200 bg-blue-50/70 shadow-sm',
    dotClassName: 'bg-blue-500',
  },
};

export const DEFAULT_NOTIFICATION_META: NotificationTypeMeta = {
  badgeClassName: 'bg-slate-900 text-white',
  cardClassName: 'hover:border-slate-300 hover:bg-slate-50',
  unreadCardClassName: 'border-blue-200 bg-blue-50/70 shadow-sm',
  dotClassName: 'bg-blue-600',
};
