export const NOTIFICATION_TYPE_LABEL_KEYS: Record<string, string> = {
  FOOTBALL_TEAM_INVITED: 'notificationType_FOOTBALL_TEAM_INVITED',
  FOOTBALL_TEAM_INVITE_ACCEPTED: 'notificationType_FOOTBALL_TEAM_INVITE_ACCEPTED',
  FOOTBALL_TEAM_INVITE_DECLINED: 'notificationType_FOOTBALL_TEAM_INVITE_DECLINED',
  FOOTBALL_TEAM_INVITE_CANCELLED: 'notificationType_FOOTBALL_TEAM_INVITE_CANCELLED',
  FOOTBALL_TEAM_ROLE_CHANGED: 'notificationType_FOOTBALL_TEAM_ROLE_CHANGED',
  FOOTBALL_TEAM_MEMBER_REMOVED: 'notificationType_FOOTBALL_TEAM_MEMBER_REMOVED',
  FOOTBALL_TEAM_MEMBER_LEFT: 'notificationType_FOOTBALL_TEAM_MEMBER_LEFT',
  COMMUNITY_INVITED: 'notificationType_COMMUNITY_INVITED',
  COMMUNITY_ROLE_PROMOTED: 'notificationType_COMMUNITY_ROLE_PROMOTED',
  COMMUNITY_ROLE_DEMOTED: 'notificationType_COMMUNITY_ROLE_DEMOTED',
  COMMUNITY_KICKED: 'notificationType_COMMUNITY_KICKED',
  COMMUNITY_INVITE_REVOKED: 'notificationType_COMMUNITY_INVITE_REVOKED',
  COMMUNITY_OWNERSHIP_TRANSFERRED: 'notificationType_COMMUNITY_OWNERSHIP_TRANSFERRED',
  COMMUNITY_BANNED: 'notificationType_COMMUNITY_BANNED',
  COMMUNITY_UNBANNED: 'notificationType_COMMUNITY_UNBANNED',
  TOURNAMENT_REGISTER_PENDING: 'notificationType_TOURNAMENT_REGISTER_PENDING',
  TOURNAMENT_REGISTER_SUCCESS: 'notificationType_TOURNAMENT_REGISTER_SUCCESS',
  TOURNAMENT_REGISTER_REJECTED: 'notificationType_TOURNAMENT_REGISTER_REJECTED',
  TOURNAMENT_PARTICIPANT_NEW: 'notificationType_TOURNAMENT_PARTICIPANT_NEW',
  TOURNAMENT_TEAM_PENDING: 'notificationType_TOURNAMENT_TEAM_PENDING',
  TOURNAMENT_TEAM_COMPLETED: 'notificationType_TOURNAMENT_TEAM_COMPLETED',
  TOURNAMENT_TEAMMATE_JOINED: 'notificationType_TOURNAMENT_TEAMMATE_JOINED',
  TOURNAMENT_WITHDRAWN: 'notificationType_TOURNAMENT_WITHDRAWN',
  TOURNAMENT_KICKED: 'notificationType_TOURNAMENT_KICKED',
  TOURNAMENT_FULL_CANCELLED: 'notificationType_TOURNAMENT_FULL_CANCELLED',
  TOURNAMENT_TEAM_TIMEOUT: 'notificationType_TOURNAMENT_TEAM_TIMEOUT',
  TOURNAMENT_FOOTBALL_ROSTER_CONFIRMATION: 'notificationType_TOURNAMENT_FOOTBALL_ROSTER_CONFIRMATION',
  PARTNER_INVITE_RECEIVED: 'notificationType_PARTNER_INVITE_RECEIVED',
  PARTNER_INVITE_ACCEPTED: 'notificationType_PARTNER_INVITE_ACCEPTED',
  PARTNER_INVITE_REJECTED: 'notificationType_PARTNER_INVITE_REJECTED',
  PARTNER_INVITE_CANCELLED: 'notificationType_PARTNER_INVITE_CANCELLED',
  TOURNAMENT_PAYMENT_COMPLETED: 'notificationType_TOURNAMENT_PAYMENT_COMPLETED',
  TOURNAMENT_CANCELLED: 'notificationType_TOURNAMENT_CANCELLED',
  TOURNAMENT_RESERVED_SLOT_ASSIGNED: 'notificationType_TOURNAMENT_RESERVED_SLOT_ASSIGNED',
  TOURNAMENT_PUBLISH_APPROVED: 'notificationType_TOURNAMENT_PUBLISH_APPROVED',
  TOURNAMENT_PUBLISH_REJECTED: 'notificationType_TOURNAMENT_PUBLISH_REJECTED',
  TOURNAMENT_SUSPENDED: 'notificationType_TOURNAMENT_SUSPENDED',
  TOURNAMENT_UNSUSPENDED: 'notificationType_TOURNAMENT_UNSUSPENDED',
  TOURNAMENT_DELETE_APPROVED: 'notificationType_TOURNAMENT_DELETE_APPROVED',
  TOURNAMENT_DELETE_REJECTED: 'notificationType_TOURNAMENT_DELETE_REJECTED',
  VERIFICATION_APPROVED: 'notificationType_VERIFICATION_APPROVED',
  VERIFICATION_REJECTED: 'notificationType_VERIFICATION_REJECTED',
  USER_BANNED: 'notificationType_USER_BANNED',
  USER_UNBANNED: 'notificationType_USER_UNBANNED',
  MATCH_SCHEDULED: 'notificationType_MATCH_SCHEDULED',
  MATCH_REMINDER: 'notificationType_MATCH_REMINDER',
  MATCH_COMPLETED: 'notificationType_MATCH_COMPLETED',
  REFEREE_INVITED: 'notificationType_REFEREE_INVITED',
  REFEREE_INVITE_REVOKED: 'notificationType_REFEREE_INVITE_REVOKED',
  REFEREE_INVITE_ACCEPTED: 'notificationType_REFEREE_INVITE_ACCEPTED',
  REFEREE_INVITE_DECLINED: 'notificationType_REFEREE_INVITE_DECLINED',
  REFEREE_ASSIGNED: 'notificationType_REFEREE_ASSIGNED',
  STAFF_ADDED: 'notificationType_STAFF_ADDED',
  PAYOUT_APPROVED: 'notificationType_PAYOUT_APPROVED',
  PAYOUT_REJECTED: 'notificationType_PAYOUT_REJECTED',
  COMMUNITY_POST_MENTIONED: 'notificationType_COMMUNITY_POST_MENTIONED',
  COMMUNITY_POST_COMMENTED: 'notificationType_COMMUNITY_POST_COMMENTED',
  COMMUNITY_POST_APPROVED: 'notificationType_COMMUNITY_POST_APPROVED',
};

export interface NotificationTypeMeta {
  badgeClassName: string;
  cardClassName: string;
  unreadCardClassName: string;
  dotClassName: string;
}

export const NOTIFICATION_TYPE_META: Record<string, NotificationTypeMeta> = {
  FOOTBALL_TEAM_INVITED: {
    badgeClassName: 'bg-emerald-100 text-emerald-800',
    cardClassName: 'hover:border-emerald-200 hover:bg-emerald-50/50',
    unreadCardClassName: 'border-emerald-200 bg-emerald-50/70 shadow-sm',
    dotClassName: 'bg-emerald-500',
  },
  FOOTBALL_TEAM_INVITE_ACCEPTED: {
    badgeClassName: 'bg-emerald-100 text-emerald-800',
    cardClassName: 'hover:border-emerald-200 hover:bg-emerald-50/50',
    unreadCardClassName: 'border-emerald-200 bg-emerald-50/70 shadow-sm',
    dotClassName: 'bg-emerald-500',
  },
  FOOTBALL_TEAM_INVITE_DECLINED: {
    badgeClassName: 'bg-rose-100 text-rose-800',
    cardClassName: 'hover:border-rose-200 hover:bg-rose-50/50',
    unreadCardClassName: 'border-rose-200 bg-rose-50/70 shadow-sm',
    dotClassName: 'bg-rose-500',
  },
  FOOTBALL_TEAM_INVITE_CANCELLED: {
    badgeClassName: 'bg-slate-200 text-slate-700',
    cardClassName: 'hover:border-slate-300 hover:bg-slate-50',
    unreadCardClassName: 'border-slate-300 bg-slate-100 shadow-sm',
    dotClassName: 'bg-slate-500',
  },
  FOOTBALL_TEAM_ROLE_CHANGED: {
    badgeClassName: 'bg-blue-100 text-blue-800',
    cardClassName: 'hover:border-blue-200 hover:bg-blue-50/50',
    unreadCardClassName: 'border-blue-200 bg-blue-50/70 shadow-sm',
    dotClassName: 'bg-blue-500',
  },
  FOOTBALL_TEAM_MEMBER_REMOVED: {
    badgeClassName: 'bg-rose-100 text-rose-800',
    cardClassName: 'hover:border-rose-200 hover:bg-rose-50/50',
    unreadCardClassName: 'border-rose-200 bg-rose-50/70 shadow-sm',
    dotClassName: 'bg-rose-500',
  },
  FOOTBALL_TEAM_MEMBER_LEFT: {
    badgeClassName: 'bg-amber-100 text-amber-800',
    cardClassName: 'hover:border-amber-200 hover:bg-amber-50/50',
    unreadCardClassName: 'border-amber-200 bg-amber-50/70 shadow-sm',
    dotClassName: 'bg-amber-500',
  },
  COMMUNITY_INVITED: {
    badgeClassName: 'bg-blue-100 text-blue-800',
    cardClassName: 'hover:border-blue-200 hover:bg-blue-50/50',
    unreadCardClassName: 'border-blue-200 bg-blue-50/80 shadow-sm',
    dotClassName: 'bg-blue-500',
  },
  COMMUNITY_ROLE_PROMOTED: {
    badgeClassName: 'bg-blue-100 text-blue-800',
    cardClassName: 'hover:border-blue-200 hover:bg-blue-50/50',
    unreadCardClassName: 'border-blue-200 bg-blue-50/75 shadow-sm',
    dotClassName: 'bg-blue-500',
  },
  COMMUNITY_ROLE_DEMOTED: {
    badgeClassName: 'bg-amber-100 text-amber-800',
    cardClassName: 'hover:border-amber-200 hover:bg-amber-50/50',
    unreadCardClassName: 'border-amber-200 bg-amber-50/75 shadow-sm',
    dotClassName: 'bg-amber-500',
  },
  COMMUNITY_KICKED: {
    badgeClassName: 'bg-rose-100 text-rose-800',
    cardClassName: 'hover:border-rose-200 hover:bg-rose-50/50',
    unreadCardClassName: 'border-slate-200 bg-rose-50/75 shadow-sm',
    dotClassName: 'bg-rose-500',
  },
  COMMUNITY_INVITE_REVOKED: {
    badgeClassName: 'bg-slate-200 text-slate-700',
    cardClassName: 'hover:border-slate-300 hover:bg-slate-50',
    unreadCardClassName: 'border-slate-300 bg-slate-100 shadow-sm',
    dotClassName: 'bg-slate-500',
  },
  COMMUNITY_OWNERSHIP_TRANSFERRED: {
    badgeClassName: 'bg-amber-100 text-amber-800',
    cardClassName: 'hover:border-amber-200 hover:bg-amber-50/50',
    unreadCardClassName: 'border-amber-200 bg-amber-50/75 shadow-sm',
    dotClassName: 'bg-amber-500',
  },
  COMMUNITY_BANNED: {
    badgeClassName: 'bg-rose-100 text-rose-800',
    cardClassName: 'hover:border-rose-200 hover:bg-rose-50/50',
    unreadCardClassName: 'border-slate-200 bg-rose-50/75 shadow-sm',
    dotClassName: 'bg-rose-500',
  },
  COMMUNITY_UNBANNED: {
    badgeClassName: 'bg-blue-100 text-blue-800',
    cardClassName: 'hover:border-blue-200 hover:bg-blue-50/50',
    unreadCardClassName: 'border-blue-200 bg-blue-50/75 shadow-sm',
    dotClassName: 'bg-blue-500',
  },
  TOURNAMENT_REGISTER_PENDING: {
    badgeClassName: 'bg-amber-100 text-amber-800',
    cardClassName: 'hover:border-amber-200 hover:bg-amber-50/50',
    unreadCardClassName: 'border-amber-200 bg-amber-50/70 shadow-sm',
    dotClassName: 'bg-amber-500',
  },
  TOURNAMENT_TEAM_PENDING: {
    badgeClassName: 'bg-amber-100 text-amber-800',
    cardClassName: 'hover:border-amber-200 hover:bg-amber-50/50',
    unreadCardClassName: 'border-amber-200 bg-amber-50/70 shadow-sm',
    dotClassName: 'bg-amber-500',
  },
  TOURNAMENT_FOOTBALL_ROSTER_CONFIRMATION: {
    badgeClassName: 'bg-amber-100 text-amber-800',
    cardClassName: 'hover:border-amber-200 hover:bg-amber-50/50',
    unreadCardClassName: 'border-amber-200 bg-amber-50/80 shadow-sm',
    dotClassName: 'bg-amber-500',
  },
  TOURNAMENT_TEAM_COMPLETED: {
    badgeClassName: 'bg-emerald-100 text-emerald-800',
    cardClassName: 'hover:border-emerald-200 hover:bg-emerald-50/50',
    unreadCardClassName: 'border-emerald-200 bg-emerald-50/70 shadow-sm',
    dotClassName: 'bg-emerald-500',
  },
  TOURNAMENT_TEAMMATE_JOINED: {
    badgeClassName: 'bg-blue-100 text-blue-800',
    cardClassName: 'hover:border-blue-200 hover:bg-blue-50/50',
    unreadCardClassName: 'border-blue-200 bg-blue-50/70 shadow-sm',
    dotClassName: 'bg-blue-500',
  },
  PARTNER_INVITE_RECEIVED: {
    badgeClassName: 'bg-blue-100 text-blue-800',
    cardClassName: 'hover:border-blue-200 hover:bg-blue-50/50',
    unreadCardClassName: 'border-blue-200 bg-blue-50/70 shadow-sm',
    dotClassName: 'bg-blue-500',
  },
  PARTNER_INVITE_ACCEPTED: {
    badgeClassName: 'bg-emerald-100 text-emerald-800',
    cardClassName: 'hover:border-emerald-200 hover:bg-emerald-50/50',
    unreadCardClassName: 'border-emerald-200 bg-emerald-50/70 shadow-sm',
    dotClassName: 'bg-emerald-500',
  },
  PARTNER_INVITE_REJECTED: {
    badgeClassName: 'bg-rose-100 text-rose-800',
    cardClassName: 'hover:border-rose-200 hover:bg-rose-50/50',
    unreadCardClassName: 'border-rose-200 bg-rose-50/70 shadow-sm',
    dotClassName: 'bg-rose-500',
  },
  PARTNER_INVITE_CANCELLED: {
    badgeClassName: 'bg-rose-100 text-rose-800',
    cardClassName: 'hover:border-rose-200 hover:bg-rose-50/50',
    unreadCardClassName: 'border-rose-200 bg-rose-50/70 shadow-sm',
    dotClassName: 'bg-rose-500',
  },
  TOURNAMENT_REGISTER_REJECTED: {
    badgeClassName: 'bg-rose-100 text-rose-800',
    cardClassName: 'hover:border-rose-200 hover:bg-rose-50/50',
    unreadCardClassName: 'border-slate-200 bg-rose-50/70 shadow-sm',
    dotClassName: 'bg-rose-500',
  },
  TOURNAMENT_KICKED: {
    badgeClassName: 'bg-rose-100 text-rose-800',
    cardClassName: 'hover:border-rose-200 hover:bg-rose-50/50',
    unreadCardClassName: 'border-slate-200 bg-rose-50/70 shadow-sm',
    dotClassName: 'bg-rose-500',
  },
  TOURNAMENT_CANCELLED: {
    badgeClassName: 'bg-rose-100 text-rose-800',
    cardClassName: 'hover:border-rose-200 hover:bg-rose-50/50',
    unreadCardClassName: 'border-slate-200 bg-rose-50/70 shadow-sm',
    dotClassName: 'bg-rose-500',
  },
  TOURNAMENT_RESERVED_SLOT_ASSIGNED: {
    badgeClassName: 'bg-blue-100 text-blue-800',
    cardClassName: 'hover:border-blue-200 hover:bg-blue-50/50',
    unreadCardClassName: 'border-blue-200 bg-blue-50/70 shadow-sm',
    dotClassName: 'bg-blue-500',
  },
  TOURNAMENT_PUBLISH_APPROVED: {
    badgeClassName: 'bg-emerald-100 text-emerald-800',
    cardClassName: 'hover:border-emerald-200 hover:bg-emerald-50/50',
    unreadCardClassName: 'border-emerald-200 bg-emerald-50/70 shadow-sm',
    dotClassName: 'bg-emerald-500',
  },
  TOURNAMENT_PUBLISH_REJECTED: {
    badgeClassName: 'bg-rose-100 text-rose-800',
    cardClassName: 'hover:border-rose-200 hover:bg-rose-50/50',
    unreadCardClassName: 'border-slate-200 bg-rose-50/70 shadow-sm',
    dotClassName: 'bg-rose-500',
  },
  TOURNAMENT_SUSPENDED: {
    badgeClassName: 'bg-amber-100 text-amber-800',
    cardClassName: 'hover:border-amber-200 hover:bg-amber-50/50',
    unreadCardClassName: 'border-amber-200 bg-amber-50/70 shadow-sm',
    dotClassName: 'bg-amber-500',
  },
  TOURNAMENT_UNSUSPENDED: {
    badgeClassName: 'bg-blue-100 text-blue-800',
    cardClassName: 'hover:border-blue-200 hover:bg-blue-50/50',
    unreadCardClassName: 'border-blue-200 bg-blue-50/70 shadow-sm',
    dotClassName: 'bg-blue-500',
  },
  TOURNAMENT_DELETE_APPROVED: {
    badgeClassName: 'bg-slate-200 text-slate-800',
    cardClassName: 'hover:border-slate-300 hover:bg-slate-50',
    unreadCardClassName: 'border-slate-300 bg-slate-100 shadow-sm',
    dotClassName: 'bg-slate-500',
  },
  TOURNAMENT_DELETE_REJECTED: {
    badgeClassName: 'bg-amber-100 text-amber-800',
    cardClassName: 'hover:border-amber-200 hover:bg-amber-50/50',
    unreadCardClassName: 'border-amber-200 bg-amber-50/70 shadow-sm',
    dotClassName: 'bg-amber-500',
  },
  VERIFICATION_APPROVED: {
    badgeClassName: 'bg-emerald-100 text-emerald-800',
    cardClassName: 'hover:border-emerald-200 hover:bg-emerald-50/50',
    unreadCardClassName: 'border-emerald-200 bg-emerald-50/70 shadow-sm',
    dotClassName: 'bg-emerald-500',
  },
  VERIFICATION_REJECTED: {
    badgeClassName: 'bg-rose-100 text-rose-800',
    cardClassName: 'hover:border-rose-200 hover:bg-rose-50/50',
    unreadCardClassName: 'border-slate-200 bg-rose-50/70 shadow-sm',
    dotClassName: 'bg-rose-500',
  },
  USER_BANNED: {
    badgeClassName: 'bg-rose-100 text-rose-800',
    cardClassName: 'hover:border-rose-200 hover:bg-rose-50/50',
    unreadCardClassName: 'border-slate-200 bg-rose-50/70 shadow-sm',
    dotClassName: 'bg-rose-500',
  },
  USER_UNBANNED: {
    badgeClassName: 'bg-blue-100 text-blue-800',
    cardClassName: 'hover:border-blue-200 hover:bg-blue-50/50',
    unreadCardClassName: 'border-blue-200 bg-blue-50/70 shadow-sm',
    dotClassName: 'bg-blue-500',
  },
  TOURNAMENT_PAYMENT_COMPLETED: {
    badgeClassName: 'bg-emerald-100 text-emerald-800',
    cardClassName: 'hover:border-emerald-200 hover:bg-emerald-50/50',
    unreadCardClassName: 'border-emerald-200 bg-emerald-50/70 shadow-sm',
    dotClassName: 'bg-emerald-500',
  },
  PAYOUT_APPROVED: {
    badgeClassName: 'bg-emerald-100 text-emerald-800',
    cardClassName: 'hover:border-emerald-200 hover:bg-emerald-50/50',
    unreadCardClassName: 'border-emerald-200 bg-emerald-50/70 shadow-sm',
    dotClassName: 'bg-emerald-500',
  },
  PAYOUT_REJECTED: {
    badgeClassName: 'bg-rose-100 text-rose-800',
    cardClassName: 'hover:border-rose-200 hover:bg-rose-50/50',
    unreadCardClassName: 'border-slate-200 bg-rose-50/70 shadow-sm',
    dotClassName: 'bg-rose-500',
  },
  MATCH_SCHEDULED: {
    badgeClassName: 'bg-blue-100 text-blue-800',
    cardClassName: 'hover:border-blue-200 hover:bg-blue-50/50',
    unreadCardClassName: 'border-blue-200 bg-blue-50/70 shadow-sm',
    dotClassName: 'bg-blue-500',
  },
  MATCH_REMINDER: {
    badgeClassName: 'bg-amber-100 text-amber-800',
    cardClassName: 'hover:border-amber-200 hover:bg-amber-50/50',
    unreadCardClassName: 'border-amber-200 bg-amber-50/70 shadow-sm',
    dotClassName: 'bg-amber-500',
  },
  MATCH_COMPLETED: {
    badgeClassName: 'bg-blue-100 text-blue-800',
    cardClassName: 'hover:border-blue-200 hover:bg-blue-50/50',
    unreadCardClassName: 'border-blue-200 bg-blue-50/70 shadow-sm',
    dotClassName: 'bg-blue-500',
  },
  REFEREE_INVITED: {
    badgeClassName: 'bg-amber-100 text-amber-800',
    cardClassName: 'hover:border-amber-200 hover:bg-amber-50/50',
    unreadCardClassName: 'border-amber-200 bg-amber-50/70 shadow-sm',
    dotClassName: 'bg-amber-500',
  },
  REFEREE_INVITE_REVOKED: {
    badgeClassName: 'bg-slate-200 text-slate-700',
    cardClassName: 'hover:border-slate-300 hover:bg-slate-50',
    unreadCardClassName: 'border-slate-300 bg-slate-100 shadow-sm',
    dotClassName: 'bg-slate-500',
  },
  STAFF_ADDED: {
    badgeClassName: 'bg-blue-100 text-blue-800',
    cardClassName: 'hover:border-blue-200 hover:bg-blue-50/50',
    unreadCardClassName: 'border-blue-200 bg-blue-50/70 shadow-sm',
    dotClassName: 'bg-blue-500',
  },
  REFEREE_INVITE_ACCEPTED: {
    badgeClassName: 'bg-emerald-100 text-emerald-800',
    cardClassName: 'hover:border-emerald-200 hover:bg-emerald-50/50',
    unreadCardClassName: 'border-emerald-200 bg-emerald-50/70 shadow-sm',
    dotClassName: 'bg-emerald-500',
  },
  REFEREE_INVITE_DECLINED: {
    badgeClassName: 'bg-rose-100 text-rose-800',
    cardClassName: 'hover:border-rose-200 hover:bg-rose-50/50',
    unreadCardClassName: 'border-slate-200 bg-rose-50/70 shadow-sm',
    dotClassName: 'bg-rose-500',
  },
  REFEREE_ASSIGNED: {
    badgeClassName: 'bg-blue-100 text-blue-800',
    cardClassName: 'hover:border-blue-200 hover:bg-blue-50/50',
    unreadCardClassName: 'border-blue-200 bg-blue-50/70 shadow-sm',
    dotClassName: 'bg-blue-500',
  },
  COMMUNITY_POST_MENTIONED: {
    badgeClassName: 'bg-indigo-100 text-indigo-800 font-semibold',
    cardClassName: 'hover:border-indigo-200 hover:bg-indigo-50/50',
    unreadCardClassName: 'border-indigo-200 bg-indigo-50/70 shadow-sm',
    dotClassName: 'bg-indigo-600',
  },
  COMMUNITY_POST_COMMENTED: {
    badgeClassName: 'bg-sky-100 text-sky-800 font-semibold',
    cardClassName: 'hover:border-sky-200 hover:bg-sky-50/50',
    unreadCardClassName: 'border-sky-200 bg-sky-50/70 shadow-sm',
    dotClassName: 'bg-sky-600',
  },
  COMMUNITY_POST_APPROVED: {
    badgeClassName: 'bg-emerald-100 text-emerald-800 font-semibold',
    cardClassName: 'hover:border-emerald-200 hover:bg-emerald-50/50',
    unreadCardClassName: 'border-emerald-200 bg-emerald-50/70 shadow-sm',
    dotClassName: 'bg-emerald-500',
  },
};

export const DEFAULT_NOTIFICATION_META: NotificationTypeMeta = {
  badgeClassName: 'bg-slate-900 text-white',
  cardClassName: 'hover:border-slate-300 hover:bg-slate-50',
  unreadCardClassName: 'border-blue-200 bg-blue-50/70 shadow-sm',
  dotClassName: 'bg-blue-600',
};

